services:
  - type: web
    name: crystal-hits-panel
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: crystal-hits-super-secret-key-production-2026
      - key: DISCORD_CLIENT_SECRET
        value: 99cnjlSBj6QJ5kv23GvlgFmE2ES1kI6B
      - key: DATABASE_URL
        fromDatabase:
          name: crystal-hits-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: crystal-hits-db
    plan: free
